name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build Type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Extract native-android folder
      run: |
        if [ -f native-android.zip ]; then
          unzip native-android.zip
        fi
        
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'
        
    - name: Install Gradle and regenerate wrapper
      run: |
        cd native-android
        # Download and install Gradle
        wget https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
        unzip -q gradle-7.4.2-bin.zip
        export PATH=$PATH:$(pwd)/gradle-7.4.2/bin
        
        # Regenerate wrapper with known working version
        gradle-7.4.2/bin/gradle wrapper --gradle-version=7.4.2
        chmod +x ./gradlew
        
    - name: Build Debug APK
      run: |
        cd native-android
        ./gradlew assembleDebug --stacktrace
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: native-android/app/build/outputs/apk/debug/*.apk
