name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build Type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Debug ZIP contents
      run: |
        echo "=== Files in repository ==="
        ls -la
        echo "=== Extracting ZIP ==="
        if [ -f native-android.zip ]; then
          unzip native-android.zip
          echo "=== Files after extraction ==="
          ls -la
          echo "=== Looking for Android project files ==="
          find . -name "gradlew" -type f
          find . -name "build.gradle" -type f
        else
          echo "native-android.zip not found!"
        fi
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Find and build Android project
      run: |
        # Find where the Android project actually is
        ANDROID_DIR=$(find . -name "gradlew" -type f | head -1 | xargs dirname)
        echo "Found Android project in: $ANDROID_DIR"
        
        if [ -n "$ANDROID_DIR" ]; then
          cd "$ANDROID_DIR"
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace
        else
          echo "No Android project found!"
          exit 1
        fi
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: "**/app/build/outputs/apk/debug/*.apk"
