name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build Type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Extract native-android folder
      run: |
        if [ -f native-android.zip ]; then
          unzip native-android.zip
          ls -la native-android/
        fi
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
        unzip -q gradle-7.4.2-bin.zip
        export PATH=$PATH:$(pwd)/gradle-7.4.2/bin
        echo "$(pwd)/gradle-7.4.2/bin" >> $GITHUB_PATH
        
    - name: Build Debug APK with System Gradle
      run: |
        cd native-android
        gradle assembleDebug --stacktrace
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: native-android/app/build/outputs/apk/debug/*.apk
