name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build Type"
        required: true
        default: "debug"
        type: choice
        options: [debug, release]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: native-android   # <— no manual cd needed
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you *must* unzip a folder that isn’t tracked in git, keep this.
      # Make sure the ZIP actually contains a top-level "native-android/" directory.
      - name: Extract native-android folder (optional)
        if: ${{ hashFiles('native-android/**') == '' && hashFiles('native-android.zip') != '' }}
        run: |
          unzip -q ../native-android.zip -d .
          ls -la

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build
        env:
          # For release builds you’ll need signing env vars or a keystore step.
          # Example (if you wire them in repo secrets):
          # MYAPP_UPLOAD_STORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          # MYAPP_UPLOAD_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          # MYAPP_UPLOAD_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          # MYAPP_UPLOAD_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          BUILD_TYPE: ${{ github.event.inputs.buildType }}
        run: |
          if [ "$BUILD_TYPE" = "release" ]; then
            ./gradlew assembleRelease --stacktrace
          else
            ./gradlew assembleDebug --stacktrace
          fi

      - name: Upload APK Artifact
        if: ${{ github.event.inputs.buildType == 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-release
          path: app/build/outputs/apk/release/*.apk

      - name: Upload APK Artifact (debug)
        if: ${{ github.event.inputs.buildType != 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-debug
          path: app/build/outputs/apk/debug/*.apk
