name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build Type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'
        
    - name: Extract native-android folder
      run: |
        if [ -f native-android.zip ]; then
          unzip native-android.zip
        fi
        
    - name: Make gradlew executable
      run: |
        cd native-android
        chmod +x ./gradlew
        
    - name: Build Debug APK
      run: |
        cd native-android
        ./gradlew assembleDebug
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: native-android/app/build/outputs/apk/debug/*.apk
